"""Add repository_health table

Revision ID: 390598e9894c
Revises: 6215b1844dae
Create Date: 2026-06-24 00:35:35.791413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390598e9894c'
down_revision: Union[str, Sequence[str], None] = '6215b1844dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('architecture_score', sa.Integer(), nullable=False),
    sa.Column('testing_score', sa.Integer(), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=False),
    sa.Column('documentation_score', sa.Integer(), nullable=False),
    sa.Column('scalability_score', sa.Integer(), nullable=False),
    sa.Column('maturity_score', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_health')
    # ### end Alembic commands ###
