"""Add AST columns to Findings

Revision ID: c6f483800956
Revises: d9b8e1cd16d0
Create Date: 2026-06-25 19:37:56.318626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f483800956'
down_revision: Union[str, Sequence[str], None] = 'd9b8e1cd16d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('function_name', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('complexity', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('nesting', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'nesting')
    op.drop_column('findings', 'complexity')
    op.drop_column('findings', 'function_name')
    op.drop_column('findings', 'file_path')
    # ### end Alembic commands ###
