"""Add RecommendationFinding join table and repo constraints

Revision ID: d9b8e1cd16d0
Revises: 1704875fc688
Create Date: 2026-06-25 18:39:31.434489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b8e1cd16d0'
down_revision: Union[str, Sequence[str], None] = '1704875fc688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_findings',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id', 'finding_id')
    )
    op.add_column('repositories', sa.Column('language', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('framework', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'framework')
    op.drop_column('repositories', 'language')
    op.drop_table('recommendation_findings')
    # ### end Alembic commands ###
